Corrected STARs
vatpac-technology/simulator-scenarios pull request #110
Opened 2024-08-04 08:55 UTC by obla

Removed STARs into BN.
Minor syntax changes.

2024-09-08 01:59 UTC, alphadelta332 requested changes
all the other changes are nice though :)

2024-09-08 01:59 UTC, alphadelta332 commented on ScenarioFiles.xml
> +          <FlightPlan Active="true" Departure="YBMK" Destination="YBBN" Alternative="" Rules="I" CruiseSpeed="428" ETD="0000" ATD="0000" RFL="32000" EETHours="00" EETMins="00" FuelHours="0" FuelMins=
These STAR issues have been fixed here: https://github.com/vatpac-technology/simulator-scenarios/pull/111

No need to enter in all the STAR waypoints, the flight plan just had the wrong STAR number

2024-12-20 10:47 UTC, tylerthetiletiler commented
Should we merge or delete this?

2024-12-22 21:46 UTC, obla commented
Can we pull the cosmetic changes in, just for consistency between scenarios?

2025-01-20 23:42 UTC, obla commented
I had a look at the conflicts - not sure why they are showing? They're merely capitalisation or formatting edits.

2025-06-15 22:03 UTC, merged